direcciones_CHOICES = (
    ('Administración', 'AD'),
    ('Caserío', 'CAS'),
    ('Exterior', 'EX'),
    ('Oficina', 'OF'),
    ('Sección', 'SECC'),
    ('Aeropuerto', 'AE'),
    ('Célula', 'CU'),
    ('Ferrocarril', 'FFC'),
    ('Oficina sótano', 'OS'),
    ('Sector', 'SECT'),
    ('Agencia', 'AGN'),
    ('Centro Comercial', 'CC'),
    ('Finca', 'FI'),
    ('Oriente', 'E'),
    ('Agrupación', 'AG'),
    ('Circular', 'CQ'),
    ('Garaje', 'GJ'),
    ('Paraje', 'PRJ'),
    ('Solar', 'SL'),
    ('Almacén', 'ALM'),
    ('Circunvalar', 'CV'),
    ('Garaje Sótano', 'GS'),
    ('Parcela', 'PAR'),
    ('Sótano', 'ST'),
    ('Altillo', 'AL'),
    ('Ciudadela', 'CD'),
    ('Habitación', 'HB'),
    ('Parque', 'PQ'),
    ('Suite', 'SU'),
    ('Apartado', 'APTDO'),
    ('Condominio', 'CM'),
    ('Hacienda', 'HC'),
    ('Parqueadero', 'PA'),
    ('Supermanzana', 'SM'),
    ('Apartamento', 'AP'),
    (' Conjunto / Conjunto Residencial', 'CO'),
    ('Interior', 'IN'),
    ('Pasaje', 'PJ'),
    ('Sur', 'S'),
    ('Apartamento Sótano', 'AS'),
    ('Consultorio', 'CN'),
    ('Kilómetro', 'KM'),
    ('Paseo', 'PS'),
    ('Sur este / Sur oriente', 'SE'),
    ('Asentamiento', 'ASN'),
    ('Contador', 'CNT'),
    ('Local', 'LC'),
    ('Peatonal', 'PT'),
    ('Sur oeste / Sur occidente', 'SO'),
    ('Autopista', 'AU'),
    ('Corregimiento', 'CRG'),
    ('Local Mezzanine', 'LM'),
    ('Penthouse', 'PH'),
    ('Terminal', 'TER'),
    ('Avenida', 'AV'),
    ('Cuarto', 'QT'),
    ('Local sótano', 'LS'),
    ('Piso', 'PI'),
    ('Terraza', 'TZ'),
    ('Avenida Calle', 'AC'),
    ('Cuentas Corridas', 'CUC'),
    ('Lote', 'LT'),
    ('Plan', 'PLN'),
    ('Torre', 'TO'),
    ('Avenida Carrera', 'AK'),
    ('Departamento', 'DPTO'),
    ('Manzana', 'MZ'),
    ('Planta', 'PL'),
    ('Transversal', 'TV'),
    ('Barrio', 'BR'),
    ('Depósito', 'DP'),
    ('Mejora', 'MJ'),
    ('Plaza', 'PLZ'),
    ('Troncal', 'TC'),
    ('Bis', 'BIS'),
    ('Depósito Sótano', 'DS'),
    ('Mezzanine', 'MN'),
    ('Portería', 'PR'),
    ('Unidad', 'UN'),
    ('Bloque', 'BQ'),
    ('Descripción Adicional', 'DA'),
    ('Módulo', 'MD'),
    ('Predio', 'PD'),
    ('Unidad Residencial / Urbanización', 'UR'),
    ('Bodega', 'BG'),
    ('Diagonal', 'DG'),
    ('Municipio', 'MPIO'),
    ('Puente', 'PTE'),
    ('Variante', 'VT'),
    ('Boulevard', 'BL'),
    ('Edificio', 'ED'),
    ('Nivel', 'PI'),
    ('Puesto', 'PU'),
    ('Vereda', 'VDA'),
    ('Calle', 'CL'),
    ('Entrada', 'EN'),
    ('Norte', 'N'),
    ('Quintas', 'QNT'),
    ('Vía', 'VIA'),
    ('Camino', 'CAM'),
    ('Esquina', 'EQ'),
    ('Nor oeste / Nor occidente', 'NO'),
    ('Residencias', 'RSD'),
    ('Viaducto', 'VD'),
    ('Carrera', 'KR'),
    ('Estación', 'ES'),
    ('Nor este / Nor oriente', 'NE'),
    ('Round Point / Glorieta', 'RP'),
    ('Zona', 'ZN'),
    ('Carretera', 'CT'),
    ('Este / Oriente', 'E'),
    ('Nucleo', 'UN'),
    ('Salón', 'SA'),
    ('Zona Franca', 'ZF'),
    ('Casa', 'CA'),
    ('Etapa', 'ET'),
    ('Oeste / Occidente', 'W'),
    ('Salón Comunal', 'SC')
)
